#! /bin/bash

function install_nodejs() {
  echo "++++++++++++++++++ INSTALLING nodejs `lsb_release -ds` ++++++++++++++++++" 
  apt-get update
  apt-get install -y python-software-properties python g++ make
  add-apt-repository -y ppa:chris-lea/node.js
  apt-get update
  apt-get -q -y install nodejs
}

if [ `whoami` != "root" ]
then
  echo "ERROR: This script must be run as root"
  exit 1
fi

type -P node
if [ $? -ne 0 ] 
then
  if [ `lsb_release -is` == 'Ubuntu' ] || [ `lsb_release -is` == "Debian" ]
  then
    install_nodejs
  else
    echo PLEASE INSTALL nodejs MANUALLY 
    echo "https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager"
    exit 1
  fi
fi

type -P npm
if [ $? -ne 0 ]
then
  echo "ERROR: Your nodejs is too old, please uninstall it and run this again"
  echo "Suggestion:"
  echo "  sudo apt-get remove --purge nodejs"
  echo "  sudo apt-get clean"
  echo "  sudo apt-get autoremove"
  exit 1
fi

if [ ! -e /usr/bin/typescript ]
then
	echo "++++++++++++++++++ INSTALLING TYPESCRIPT ++++++++++++"
	npm install typescript
	npm install -g express
	npm install typescript-require
	npm install -g typescript-require
fi


